### ISSUE TITLE
"USBD_CDC_EP0_RxReady" not working at all

### ISSUE THREAD

**Issue by jianyibao** [alambe94/I-CUBE-USBD-Composite#14]
stm32_mw_usb_device/Class/CDC_ACM/Src/usbd_cdc_acm.c:

I think the following lines should be removed:
 
 
   if (hcdc == NULL)
   {
     return (uint8_t)USBD_FAIL;
   }

**Comment by alambe94** [comment]
yes, it should be after hcdc = &CDC_ACM_Class_Data[i];

line 1979

**Comment by jianyibao** [comment]
I think there is no need to check (hcdc == NULL) since it will never be NULL.

**Comment by alambe94** [comment]
In this case all instances are statically allocated. But ST uses malloc and set the pointer to NULL in deinit.
It is sanity check if we also use malloc.
