### ISSUE TITLE
The lib don't work for HID, CDC and HID+CDC

### ISSUE THREAD

**Issue by JulienGuitter** [alambe94/I-CUBE-USBD-Composite#17]
Hello, I have a project that need CDC and HID. But i can't make work this lib. I have try separately CDC or HID, and i can't, make it work. When i plug usb, the computer said, there are error in the chip. But if i use the lib of stm32cube, it works. Can you help me please. 
Thanks in advance

**Comment by alambe94** [comment]
what is your MCU

**Comment by JulienGuitter** [comment]
It's a stm32f103rb (bluepill)

**Comment by JulienGuitter** [comment]
And if i have to modificate some value, i don't know wich

**Comment by alambe94** [comment]
what is the error when you plugged in

**Comment by JulienGuitter** [comment]
![error usb](https://user-images.githubusercontent.com/62884310/171423686-e3a2f1bc-c89b-4a2d-a066-d5e0100f9bec.png)

**Comment by alambe94** [comment]
Is the MCU clock configured correctly?
External Crystal and 48MHz or cube will recalculate if USB is enabled

Is USB interrupt enabled in NVIC?

Did you call MX_USB_DEVICE_Init()?

**Comment by JulienGuitter** [comment]
Juste 
![error usb](https://user-images.githubusercontent.com/62884310/171440245-693696fb-4f8b-4f25-b536-31b9624e3fcf.png)
wich i need to activate ?

**Comment by alambe94** [comment]
Enable both USB interrupts
Last two

**Comment by JulienGuitter** [comment]
I have try but it doesn't work
when i start the debug, the code break at :


void HardFault_Handler(void)

**Comment by alambe94** [comment]
is going hard fault after executing MX_USB_DEVICE_Init()?
is usb interrupt hitting?

**Comment by JulienGuitter** [comment]
So i find my probleme, i juste forgot to check stm32f1 in conf, so now it's work but i don't know how to use HID, i past my code but it didn't work.

**Comment by JulienGuitter** [comment]
So i finaly did it, i have change the hid report desc for the basic and it's work. Thank's for your help
