### ISSUE TITLE
Wrong Endpoint name when SPKR and STM32F1_DEVICE is activated

### ISSUE THREAD

**Issue by st0ne** [alambe94/I-CUBE-USBD-Composite#4]
`HAL_PCDEx_PMAConfig((PCD_HandleTypeDef *)pdev->pData, AUDIO_OUT_EP, PCD_SNG_BUF, pma_track);`

correct would be:

`HAL_PCDEx_PMAConfig((PCD_HandleTypeDef *)pdev->pData, AUDIO_SPKR_EP, PCD_SNG_BUF, pma_track);`

**Comment by alambe94** [comment]
Thanks
Compilation error fixed.
