### ISSUE TITLE
usbd_audio_mic.h - wrong name of transfer function

### ISSUE THREAD

**Issue by st0ne** [alambe94/I-CUBE-USBD-Composite#6]
the name of the function is:
`uint8_t USBD_AUDIO_MICData_Transfer(USBD_HandleTypeDef *pdev, int16_t *audioData, uint16_t dataAmount);`

correct would be:
`uint8_t USBD_AUDIO_MIC_Data_Transfer(USBD_HandleTypeDef *pdev, int16_t *audioData, uint16_t dataAmount);`

**Comment by alambe94** [comment]
thank, function renamed.
